services:
  - type: static
    name: PurelyHome
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    publishCommand: npm run build
    staticPublishPath: dist
